### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by katrinleinweber**

### CODE REVIEW

**Comment by katrinleinweber** [comment]
You're welcome, and thanks for merging :-)

**Comment by kntsoriano** [comment]
@kytrinyx We still need to compile and push to `website-copy` for every change that gets merged here.

**Comment by kytrinyx** [comment]
@kntsoriano Yes! My question was about the workaround you had because we had some bash commands that were breaking the walkthrough. You were doing something special at some point (I think).

**Comment by kntsoriano** [comment]
@kytrinyx Ah, yes. I've written everything out regarding that in https://github.com/exercism/interactive-cli-walkthrough/blob/master/CONTRIBUTING.md#the-parser.

Thanks for reminding me! I've cleaned up `CONTRIBUTING.md` in the process.

**Pull request merged**
