### PR TITLE
Link back to dashboard (or equivalent)

### PR DESCRIPTION
**Pull request by katrinleinweber**
I found myself stuck a bit at the end of the guide when I was walking some people through it. Would it make sense to actually place a link back to the track overview? I'm not sure what "dashboard" means otherwise.

### CODE REVIEW

**Comment by katrinleinweber** [comment]
If yes, would this change propagate to https://github.com/exercism/website-copy/blob/master/walkthrough/index.html#L23 ?

**Comment by kytrinyx** [comment]
Yes, the change will propagate.

**Comment by kytrinyx** [comment]
> do we know whether tw2 takes markdown syntax?

Ok, looking at this again, I'm pretty sure the markdown syntax works.

@katrinleinweber did you compile and test this locally by any chance?

**Comment by katrinleinweber** [comment]
I did now ;-)

image

**Comment by katrinleinweber** [comment]
You're welcome, and thanks for merging :-)

**Pull request merged**
