### PR TITLE
fix typo in process -> processor

### PR DESCRIPTION
**Pull request by iranzo**
Fixes typo in selecting CLI for your system's CPU architecture

Fixes https://github.com/exercism/exercism/issues/6605

### CODE REVIEW

**Review by kytrinyx — APPROVED** [review]
@iranzo Thanks for this ✨

**Comment by kytrinyx** [comment]
@ErikSchierboom Do you have this working on your computer? I'm having trouble installing the dependencies (tried in the currently defined ruby-version, as well as a more recent stable 2.7.x version, as well as a ruby-3.1.x version).

I'll wrestle with the dependencies if I need to, but if you've already got it working I won't spend more time on it.

**Comment by ErikSchierboom** [comment]
I have got it working. I'll handle it.

**Comment by ErikSchierboom** [comment]
https://github.com/exercism/website-copy/pull/2234

**Pull request merged**
